#!/bin/sh
# Copyright (c) 2014 Heikki Hokkanen <hoxu@users.sf.net>
# License: GPLv3 or later

PATH=/sbin:$PATH

function start() {
	ipv4=$new_ip_address
	ipv6=$(ipv6calc --quiet --action conv6to4 $ipv4)
	echo "Configuring 6to4 for network interface $interface $ipv4 -> $ipv6..."
	ip tunnel add tun6to4 mode sit remote any local $ipv4
	ip link set dev tun6to4 up
	ip -6 addr add ${ipv6}1/16 dev tun6to4
	ip -6 route add 2000::/3 via ::192.88.99.1 dev tun6to4 metric 1
	ip tunnel change tun6to4 ttl 64
}

function stop() {
	echo "Deconfiguring 6to4 for network interface $interface..."
	ip -6 route flush dev tun6to4
	ip link set dev tun6to4 down
	ip tunnel del tun6to4
}

if [ -n "$new_ip_address" ]; then
	if [ "$old_ip_address" != "$new_ip_address" ]; then
		stop
		start
	fi
else
	stop
fi

